version: '3.8'

services:
  postgres:
    image: 'postgres:latest'
    container_name: order-management-payments-postgres
    ports:
      - '54321:5432'
    environment:
      POSTGRES_DB: order_management_db
      POSTGRES_USER: order_management
      POSTGRES_PASSWORD: order_management
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER" ]
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
