server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: ms-payments

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:54321}/${POSTGRES_NAME:mspaymentsdb}
    username: ${POSTGRES_USERNAME:MS_PAYMENTS}
    password: ${POSTGRES_PASSWORD:MS_PAYMENTS}
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: ${SHOW_SQL:true}
      open-in-view: false
      database-platform: org.hibernate.dialect.PostgreSQLDialect

  data:
    mongodb:
      host: ${MONGODB_HOST:localhost}
      port: ${MONGODB_PORT:27018}
      database: ${MONGODB_NAME:mspaymentsmongodb}
      auto-index-creation: true

  flyway:
    enable: true
    baseline_on_migrate: false

  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USERNAME:guest}
    password: ${RABBIT_PASSWORD:guest}
    max_retry: 3
    queues:
      fetch_payment:
        queue: order_management_payments_created_order_queue
        retry_queue: order_management_payments_created_order_retry_queue
        dead_queue: order_management_payments_created_order_dead_queue
    exchanges:
      order_management_events: order_management_events
    routing_keys:
      created_order_routing_key: created_order_routing_key
      processed_payment_routing_key: processed_payment_routing_key